//AUTOGENERATED FILE! DO NOT EDIT!
#include "../grx/graphic_types.h"
extern const bitmap_t BITMAP_ubuntu_bold_16;

extern const font_t FONT_ubuntu_bold_16;

extern const bitmap_t BITMAP_ubuntu_bold_24;

extern const font_t FONT_ubuntu_bold_24;

extern const bitmap_t BITMAP_ubuntu_bold_40;

extern const font_t FONT_ubuntu_bold_40;

extern const bitmap_t BITMAP_ubuntu_bold_32;

extern const font_t FONT_ubuntu_bold_32;

extern const bitmap_t BITMAP_ubuntu_medium_48;

extern const font_t FONT_ubuntu_medium_48;
